server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventories/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/cart/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
            - Path=/payment-service/v3/api-docs
            - Method=GET

        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/shippings/**
          default-filters:
            - TokenRelay
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
jwt:
  auth:
    converter:
      resource-id: ecommerce-platform-client
      principle-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: inventory-service
        url: /api/inventory/v3/api-docs
