server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true


spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
            - Path=/inventory-service/v3/api-docs
            - Method=GET

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
            - Path=/payment-service/v3/api-docs
            - Method=GET

        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/shipping/**
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
springdoc:
  api-docs:
    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
#      - url: /test-service/v3/api-docs
#        name: Test Service
