# Global Configuration
global:
  controller:
    current-version: "v1"
    path:
      users:
        base: "/api/users/"
      customers:
        base: "/api/customers/"
      catalog:
        base: "/api/catalog/"
        categories:
          base: "/api/catalog/categories/"
        products:
          base: "/api/catalog/products/"
        mixtures:
          base: "/api/catalog/mixtures/"
  mailserver:
    host: localhost
    port: 1025
    username: ""
    password: ""
    reset-link:
      subject: "Password Reset Request"
      body-first-part: "To reset your password, please click the following link:\n"
      body-second-part: "The link is valid for 1 hour."
      url: "http://localhost:4200/reset-password?token="
  kafka:
    topics:
      inventories:
        inventory-request: "inventory-request-topic"
        inventory-response: "inventory-response-topic"
        inventory-update: "inventory-update-topic"
      users:
        user-created: "user-created-topic"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-platform
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
keycloak:
  server:
    url: http://localhost:9090
  admin:
    realm: ecommerce-platform
    client-id: ecommerce-platform-client
    username: ecommerce-platform-rest-api
    password: secret
  target-realm: ecommerce-platform
