server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:file:./data/catalog_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  kafka:
  cache:
    type: redis
    redis:
        time-to-live: 60000
  redis:
    host: localhost
    port: 6379
