server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:file:./data/configuration_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  kafka:
    consumer:
      group-id: configuration-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.dvoracekmartin.common.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
logging:
  level:
    liquibase: INFO
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
