server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:file:./data/customer_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  kafka:
    consumer:
      group-id: customer-service-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.dvoracekmartin.common.event

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api/customer/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/customer/swagger-ui.html

kafka:
  topic:
    userCreated: user_created_topic
