server:
  port: 8085

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:file:./data/inventory_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  kafka:
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.dvoracekmartin.common.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.dvoracekmartin.common.event
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api/inventory/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/inventory/swagger-ui.html
