server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:file:./data/itinerarydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /inventory/v3/api-docs
  swagger-ui:
    enabled: true
    path: /inventory/swagger-ui.html
