server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/user_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api/user/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/user/swagger-ui.html

kafka:
  topic:
    userCreated: user_created_topic
