server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:h2:file:./data/user_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-platform
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api/user/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/user/swagger-ui.html

keycloak:
  server:
    url: http://localhost:9090
  admin:
    realm: ecommerce-platform
    client-id: ecommerce-platform-client
    username: ecommerce-platform-rest-api
    password: secret
  target-realm: ecommerce-platform

kafka:
  topic:
    userCreated: user_created_topic
