server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

spring:
  application:
    name: api-gateway-service
  profiles:
    active: docker

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/ecommerce_db}
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true

  config:
    import: configserver:http://config-server:8888

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
