server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server
    preferIpAddress: true

spring:
  application:
    name: eureka-server
  profiles:
    active: docker
