server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/ecommerce_db  # Uses environment variable from Docker
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /apiinventory/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/inventory/swagger-ui.html
