server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://inventory-service-postgres-db:5432/inventory_db  # Uses environment variable from Docker
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Alibou
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api/inventory/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/inventory/swagger-ui.html
