server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIp
spring:
  application:
    name: inventory-service
  profiles:
    active: docker

  datasource:
    url: jdbc:postgresql://postgres-db:5432/ecommerce_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
