server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-service-postgres-db:5432/user_db  # Uses environment variable from Docker
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak-service:9090/realms/Alibou
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      gateway:
        enabled: true

  springdoc:
    api-docs:
      enabled: true
      path: /api/user/v3/api-docs
    swagger-ui:
      enabled: true
      path: /api/user/swagger-ui.html

keycloak:
  server:
    url: http://localhost:9090
  admin:
    realm: ecommerce-platform
    client-id: ecommerce-platform-client
    username: ecommerce-platform-rest-api
    password: secret
  target-realm: ecommerce-platform

